PROJECT.name           = Jaymod
PROJECT.namef          = jaymod
PROJECT.namex          = ^xJay^4mod
PROJECT.website        = http://jaymod.clanfu.org
PROJECT.irc            = irc.freenode.net \#jaymod
PROJECT.author         = Jaybird
PROJECT.copyright      = Copyright (c) 2005-2011 Jaybird. All Rights Reserved.
PROJECT.versionMajor   = 2
PROJECT.versionMinor   = 2
PROJECT.versionPoint   = 0
PROJECT.buildDate      = Tue Aug 04 08:02:38 UTC 2026
PROJECT.buildStability = development
PROJECT.buildTarget    = linux64
PROJECT.repoURL        = 
PROJECT.repoUUID       = 
PROJECT.repoRev        = 0
PROJECT.repoLCRev      = 0
PROJECT.repoLCDate     = 
PROJECT.platformName   = Linux
PROJECT.platformNamef  = linux64
PROJECT.title          = Jaymod 2.2.0
PROJECT.titlex         = ^xJay^4mod ^f2.2.0
PROJECT.version        = 2.2.0
PROJECT.versionx       = ^f2.2.0
PROJECT.packageBase    = jaymod-2.2.0
PROJECT.packageBasev   = jaymod-2.2.0-linux64
PROJECT.pk3            = jaymod-2.2.0.pk3
