#define JAYMOD_name           "Jaymod"
#define JAYMOD_namef          "jaymod"
#define JAYMOD_namex          "^xJay^4mod"
#define JAYMOD_website        "http://jaymod.clanfu.org"
#define JAYMOD_irc            "irc.freenode.net #jaymod"
#define JAYMOD_author         "Jaybird"
#define JAYMOD_copyright      "Copyright (c) 2005-2011 Jaybird. All Rights Reserved."
#define JAYMOD_versionMajor   "2"
#define JAYMOD_versionMinor   "2"
#define JAYMOD_versionPoint   "0"
#define JAYMOD_versionHex     0x02020000
#define JAYMOD_buildDate      "Tue Aug 04 08:00:54 UTC 2026"
#define JAYMOD_buildStability "stable"
#define JAYMOD_buildTarget    "linux64-release"
#define JAYMOD_repoURL        ""
#define JAYMOD_repoUUID       ""
#define JAYMOD_repoRev        "0"
#define JAYMOD_repoLCRev      "0"
#define JAYMOD_repoLCDate     ""
#define JAYMOD_platformName   "Linux"
#define JAYMOD_platformNamef  "linux64"
#define JAYMOD_title          "Jaymod 2.2.0"
#define JAYMOD_titlex         "^xJay^4mod ^f2.2.0"
#define JAYMOD_version        "2.2.0"
#define JAYMOD_versionx       "^f2.2.0"
#define JAYMOD_packageBase    "jaymod-2.2.0"
#define JAYMOD_packageBasev   "jaymod-2.2.0-linux64-release"
#define JAYMOD_pk3            "jaymod-2.2.0.pk3"

#define JAYMOD_LINUX64
#define JAYMOD_STABLE
